### PR TITLE
Compatibility fixes to support symfony 3.0

### PR DESCRIPTION
**Pull request by lashus**
Please check it down. It's been working for my sf 3.0 and sf 2.6

### CODE REVIEW

**Comment by dkisselev** [comment]
It looks like your rebase didn't pull the recent changes in this repository into yours (so all the commits that happened here are in this PR as requested new commits)

Try doing a `git pull --rebase' so that those changes get pulled in and your commit is applied on top of it.

**Comment by lashus** [comment]
Ok I think I've done it :)

**Comment by dkisselev** [comment]
Looks good!

**Comment by lashus** [comment]
Ok, any idea why it fails on php 5.3.3? I guess it might be something with autoloaders?

**Comment by florianeckerstorfer** [comment]
Symfony 3 requires PHP 5.5.9. Maybe we should put out a new major version to be compatible.

🐯

**Comment by lashus** [comment]
@florianeckerstorfer we definitely should. Although with the configuration I provided it should work both with symfony 2.6+ (with legacyHelper) and 3.0. Symfony 3 forces composer to use php > 5.5.9 so it won't be a problem. I'm fixing test issues.

**Comment by dkisselev** [comment]
Your new commits seem to have un-rebased your changes, so all the old commits are back :(

I think the current solution is pretty good - detects the Symfony version and uses the appropriate syntax so deprecations are avoided as well as maintaining two release branches.

**Comment by lashus** [comment]
Fixed :) Thanks.

**Comment by dkisselev** [comment]
I just noticed that Scritinizer has identified a whole bunch of deprecation issues that I introduced in my commits,

Apparently Twig_SimpleFunction is already deprecated and equivalent to Twig_Function (the documentation on this is very unclear). I believe that might need to be fixed. @florianeckerstorfer I noticed that you're burning through all the old tickets right this second, but I'm going to take a look right now to see if replacing SImpleFunction with Function still works.

**Comment by florianeckerstorfer** [comment]
Great thanks a lot for your hard work. Yeah I cleaned up a few of the old issues, hopefully I can test and merge this one tomorrow.

**Comment by dkisselev** [comment]
Ok, so it looks like Scrutinizer is jumping the gun a bit on those notices.

Basically, Twig wasn't happy with the API that they had for Twig_Function, so they're pushing everyone onto SimpleFunction for 2.0, which follows the new API, and immediately deprecated it. In Twig 3.0, they're going to bring back Twig_Function with the new API.

*Technically* the deprecation notice isn't wrong, but the current implementation is the recommended way of doing things, and will remain that way until Twig 2.0 comes out when we can use Twig_Function again. We physically cannot fix the issue right now because Twig_Function doesn't exist in 1.x anymore.

**Pull request merged**
