### PR TITLE
Compatibility for symfony 3.0

### PR DESCRIPTION
**Pull request by lashus**
Hello,

I have made changes that allows to use this bundle along with symfony 3.0 and twig 2.0. Tests are passing. Please take a look.

### CODE REVIEW

**Comment by dkisselev** [comment]
Why did you bump the PHP requirement up to 5.5? Like I said, we still need to support SF2.8 which supports PHP 5.4.

Ideally please try to squash the changes into a single commit

**Comment by lashus** [comment]
I have realised afterwards that it needs more rewriting than i originally thought. thats why i closed this request, I'll reopen it when im done.

Btw didnt symfony rised this to minimum of 5.5 in v2.6?

**Comment by dkisselev** [comment]
No, because Symfony is very strict on backwards compatibility, any release in the 2.x branch is compatible with 5.3.3, upto/including 2.8: https://github.com/symfony/symfony/blob/2.8/composer.json

3.0 raises the required version to 5.9.9: https://github.com/symfony/symfony/blob/3.0/composer.json

**Comment by lashus** [comment]
I'll have that in mind. Thanks. Although there will be a problem with BC because the templates sre changed too. Do you have a proposition for how could we solve this?

The main issue is that parameters like read_only, pattern etc. Are removed and moved to attr.

**Pull request closed without merging**
