### PR TITLE
Upgraded Twig template to be compatible with 2.7 (#377)

### PR DESCRIPTION
**Pull request by althaus**
This updates the bundle to Symfony 2.7

### CODE REVIEW

**Comment by manuonet** [comment]
hi i got a problem with the 2.7 upgrade and Twig optimizer : 

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Optimizer mode "" is not valid.' in /home/notroot/www/sign.groupeonet.com/vendor/twig/twig/lib/Twig/NodeVisitor/Optimizer.php:44\nStack trace:\n#0 /home/notroot/www/sign.groupeonet.com/vendor/twig/twig/lib/Twig/Extension/Optimizer.php(25): Twig_NodeVisitor_Optimizer->__construct(NULL)\n#1 /home/notroot/www/sign.groupeonet.com/vendor/twig/twig/lib/Twig/Environment.php(1252): Twig_Extension_Optimizer->getNodeVisitors()\n#2 /home/notroot/www/sign.groupeonet.com/vendor/twig/twig/lib/Twig/Environment.php(1197): Twig_Environment->initExtension(Object(Twig_Extension_Optimizer))\n#3 /home/notroot/www/sign.groupeonet.com/vendor/twig/twig/lib/Twig/Environment.php(1130): Twig_Environment->initExtensions()\n#4 /home/notroot/www/sign.groupeonet.com/vendor/twig/twig/lib/Twig/Lexer.php(367): Twig_Environment->getUnaryOperators()\n#5 /home/notroot/www/sign.groupeonet.com/vendor/twig/twig/lib/Twig/Lexer.php(65): Twig_Lexer->getOperatorRegex()\n#6 /home/notroot/www/sign.group in /home/notroot/www/sign.groupeonet.com/vendor/symfony/symfony/src/Symfony/Bundle/TwigBundle/Controller/ExceptionController.php on line 37

**Comment by althaus** [comment]
@manuonet Using my modified Twig template? Hmm... I just copied the changes from the Symfony files.

**Comment by althaus** [comment]
@florianeckerstorfer Give me a note, if you prefer squashed commits.

**Comment by manuonet** [comment]
Hi
Thanks a lot for your help. But I think I made a mistake when I choose your post.
Have a nice day

De : Matthias Althaus [mailto:notifications@github.com]
Envoyé : jeudi 4 juin 2015 12:46
À : braincrafted/bootstrap-bundle
Cc : Tesson Emmanuel
Objet : Re: [bootstrap-bundle] Upgraded Twig template to be compatible with 2.7 (#377) (#378)


@florianeckerstorfer<https://github.com/florianeckerstorfer> Give me a note, if you prefer squashed commits.

**Comment by Restless-ET** [comment]
@florianeckerstorfer I believe this can be closed now that #382 has been merged. :)

PS- Unless you prefer to change the minimum required version of Symfony to 2.7.

**Pull request closed without merging**
