### PR TITLE
Replaced 'sameas' with 'same' (issue #414)

### PR DESCRIPTION
**Pull request by bartwesselink**
Replaced 'sameas' with 'same' (issue #414) to achieve Symfony 3.0 compability.

### CODE REVIEW

**Comment by dkisselev** [comment]
Are you seeing any more deprecations in your apps after this fix? (just trying to ask everyone I can to get coverage)

**Comment by bartwesselink** [comment]
I will check on that tomorrow.

**Comment by bartwesselink** [comment]
I did not find one.

**Comment by kYem** [comment]
I though it should be `same as` rather than `same`

As per deprecation notice
`Twig Test "sameas" is deprecated since version 1.21. Use "same as" instead in BraincraftedBootstrapBundle:Form:bootstrap.html.twig at line 39`

**Comment by bartwesselink** [comment]
Sorry. Did not see that. It should be fixed.

**Comment by kYem** [comment]
Can we get this merged in?

**Pull request merged**
