### PR TITLE
Added button twig function

### PR DESCRIPTION
**Pull request by bigfoot90**
The function
```twig
{{ button() }}
```
Will render to
```html
<button class="btn btn-default btn-md" type="submit"></button>
```

The function
```twig
{{ button_link() }}
```
Will render to
```html
<a href="#" class="btn btn-default btn-md"></a>
```

You can also customize the buttons with options.
```twig
{{ button({
            'id': 'test_button',
            'label': 'Test',
            'tooltip': 'Test',
            'class': 'my-class',
            'icon': 'check',
            'type': 'sucess',
            'size': 'sm',
            'submit': false,
            'attr': {
                'data-confirm': 'Are you sure?'
            },
}) }}
```
Will render to
```html
<button id="test_button" class="btn btn-sucess btn-sm my-class" type="button" title="Test" data-confirm="Are you sure?"><i class="fa fa-check"></i> Test</button>
```

The function
```twig
{{ button_link({
            'url': 'example.com',
            'id': 'test_button',
            'label': 'Test',
            'tooltip': 'Test',
            'class': 'my-class',
            'icon': 'check',
            'type': 'sucess',
            'size': 'sm',
            'attr': {
                'data-confirm': 'Are you sure?'
            },
}) }}
```
Will render to
```html
<a id="test_button" href="example.com" class="btn btn-sucess btn-sm my-class" title="Test" data-confirm="Are you sure?"><i class="fa fa-check"></i> Test</a>
```

### CODE REVIEW

**Comment by bigfoot90** [comment]
@florianeckerstorfer ping

**Comment by bigfoot90** [comment]
@florianeckerstorfer Done ;)

**Comment by florianeckerstorfer** [comment]
Thanks. I just noticed one last thing. Could you add the space to the individual variables instead of the `$button`? Before `id`, `href`, etc. Makes the generated HTML code nicer.

**Comment by bigfoot90** [comment]
Updated PR post message

**Comment by bigfoot90** [comment]
Question: some times I need to add  an extra attribute to the buttons ```data-confirm="Continue?"```, can I add the code here?

**Comment by florianeckerstorfer** [comment]
If you do it in a way that it is general, like `attr` in Symfony form fields.

**Comment by bigfoot90** [comment]
Done

**Comment by florianeckerstorfer** [comment]
Mmh, I think you should take into account the other attributes as well. For example, what happens if a user sets the `[attr][class]` attribute.

**Comment by bigfoot90** [comment]
You should not set the ```class``` inside attrubutes but in function options directly.

But I will rework attributes soon.

**Comment by bigfoot90** [comment]
Now?

**Comment by florianeckerstorfer** [comment]
Thanks.

**Comment by bigfoot90** [comment]
Can you tell me when you put new tag with this function?

**Comment by bigfoot90** [comment]
Updated first post.
The function ```button_link``` with option was not updated from last commit

**Pull request merged**
